[meta]
title="Semantic Search with OpenAI QA"
description="""\
    Provide context to chatGPT using data stored in SingleStoreDB. \
    """
icon="crystal-ball"
tags=["openai", "vectordb", "openai"]
destinations=["spaces"]
