[meta]
authors = [
    {name="Tim Green", email="tgreen@singlestore.com"},
    {name="Kevin Smith", email="ksmith@singlestore.com"},
]

[meta.urls]
homepage = "https://singlestore.com"
documentation = "https://docs.singlestore.com"

[samples]
display = [
    "getting-started-with-notebooks",
    "notebook-basics",
    "image-matching-with-sql",
    "movie-recommendation",
    "semantic-search-with-openai-qa",
    "semantic-search-with-openai-embedding-creation",
    "atlas-and-kai",
]
