[meta]
title="Hybrid Search"
description="""\
    Hybrid search combines keyword search with semantic search,
    aiming to provide more accurate results.
    """
tags=["openai"]
icon="vector-circle"
destinations=["spaces"]
